name: docs
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      work:
        description: 작업 트리거
        required: false
  push:
    branches:
      - main
    paths:
      - "docs/**"
  workflow_run:
    workflows: [E2E]
    types: [completed]

env:
  CI: true

jobs:
  docs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install

      - name: build docusaurus
        working-directory: docs
        run: |
          pnpm run build
        env:
          KAKAOMAP_API_KEY: ${{ secrets.KAKAOMAP_API_KEY }}
          NODE_ENV: development
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/build
          cname: react-kakao-maps-sdk.jaeseokim.dev
