name: pr-e2e
on:
  pull_request:
    branches: [main]

env:
  CI: true
  KAKAOMAP_API_KEY: ${{ secrets.KAKAOMAP_API_KEY }}
  VITE_KAKAOMAP_API_KEY: ${{ secrets.KAKAOMAP_API_KEY }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        working-directory: packages/react-kakao-maps-sdk
        run: npx playwright install --with-deps chromium
      - name: Make Playwright tests snapshot
        working-directory: packages/react-kakao-maps-sdk
        run: |
          pnpm run test -u
      - name: Run Playwright tests
        working-directory: packages/react-kakao-maps-sdk
        run: |
          pnpm run test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: pr-playwright-report
          path: packages/react-kakao-maps-sdk/playwright-report/
          retention-days: 15
